import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-[#879fc3] backdrop-blur-lg	'>
      <body>{children}</body>
    </html>
  )
}
